//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "raw_operation")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        column_type = "Binary(BlobSize::Blob(None))"
    )]
    pub did: Vec<u8>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub signed_operation_data: Vec<u8>,
    pub slot: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub block_number: i32,
    pub cbt: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub absn: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub osn: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
